name: Tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }} 
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip3 install codecov pytest-cov || pip3 install --user codecov pytest-cov;

    - name: Run tests
      run: |
        pip3 debug --verbose .
        pip3 install --upgrade-strategy eager -v ".[cran,forex,keel,keras,utils.estimator,utils.experiments,utils.scores]"
        coverage run --source=skdatasets/ setup.py test;
        coverage xml -o coverage.xml # explicitely exporting coverage file to be read by coverage report command.

    - name: Upload coverage to CodeClimate
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: d4b9d418d1033f48df24ad9f0083b8828a1ba312
      with:
        coverageCommand: coverage report
